# Generated by Django 4.2.7 on 2023-11-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('brend', models.CharField(max_length=255)),
                ('olchov', models.CharField(max_length=255)),
                ('narx', models.PositiveIntegerField()),
                ('miqdor', models.PositiveIntegerField()),
                ('kelgan_sana', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('qarz', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
