# Generated by Django 4.2.7 on 2023-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombor',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
